# Test configuration
[tool:pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --tb=short
    --strict-markers
    --disable-warnings
    --cov=app
    --cov=app_optimized
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-report=xml

markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    unit: marks tests as unit tests

# Coverage configuration
[coverage:run]
source = .
omit = 
    */venv/*
    */env/*
    */tests/*
    setup.py
    test_*.py

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError

# Flake8 configuration
[flake8]
max-line-length = 127
extend-ignore = E203, W503
exclude = 
    .git,
    __pycache__,
    venv,
    env,
    .venv,
    .pytest_cache

# MyPy configuration
[mypy]
python_version = 3.8
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
